# Generated by Django 4.0.5 on 2022-06-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Human',
        ),
    ]
