# Generated by Django 4.0.5 on 2022-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0002_rename_customer_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='human',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='human',
            name='phone',
        ),
    ]
