# Generated by Django 4.0.5 on 2022-07-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0004_dateentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateEntry',
        ),
    ]
